# Generated by Django 3.2.6 on 2021-08-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_background_img'),
        ('accounts', '0003_auto_20210830_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_time', models.DateTimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
