# Generated by Django 3.2.6 on 2021-08-04 11:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.TextField(default='')),
                ('full_description', tinymce.models.HTMLField()),
                ('price1', models.IntegerField(default=0)),
                ('price2', models.IntegerField(default=0)),
                ('background_img', models.ImageField(upload_to='general_files')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('short_description', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.TextField(default='')),
                ('content', tinymce.models.HTMLField(default='')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.week')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
