# Generated by Django 3.2.6 on 2021-08-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_background_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
