# Generated by Django 3.2.6 on 2021-08-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='', max_length=340),
        ),
    ]
