# Generated by Django 3.2.6 on 2021-08-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(default='Название занятия', max_length=256),
        ),
        migrations.AlterField(
            model_name='day',
            name='short_description',
            field=models.TextField(default='Короткое описание занятия'),
        ),
        migrations.AlterField(
            model_name='week',
            name='short_description',
            field=models.TextField(default='Короткое описание недели'),
        ),
    ]
