# Generated by Django 3.2.6 on 2021-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210808_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='short_description',
            field=models.TextField(default='Краткое описание занятия'),
        ),
        migrations.AlterField(
            model_name='week',
            name='short_description',
            field=models.TextField(default='Краткое описание недели'),
        ),
    ]
