# Generated by Django 3.2.6 on 2021-08-12 23:51

import apps.courses.helpers.functions
from django.db import migrations, models
import pathlib
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210809_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='background_img',
            field=models.ImageField(upload_to=apps.courses.helpers.functions.UploadToPathAndRename(pathlib.PureWindowsPath('C:/Users/lllum.DESKTOP-LFBCELC/Desktop/svetlana_website/apps/frontend/src/uploads'))),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='price1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='price2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=340),
        ),
        migrations.AlterField(
            model_name='day',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
