# Generated by Django 3.2.6 on 2022-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='background_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
