# Generated by Django 3.2.6 on 2022-02-19 06:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
