# Generated by Django 3.2.6 on 2021-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
