# Generated by Django 3.2.6 on 2021-08-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
