// General info
export const GET_GENERAL_INFO = "GET_GENERAL_INFO";
export const UPDATE_GENERAL_INFO = "UPDATE_GENERAL_INFO";
export const GET_CONTACT_INFO = "GET_CONTACT_INFO";

// Courses
export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const INVERT_COURSE_VISIBILITY = "INVERT_COURSE_VISIBILITY";
export const ADD_COURSE = "ADD_COURSE";
export const UPDATE_COURSE = "ADD_COURSE";

// Weeks
export const GET_COURSE_WEEKS = "GET_COURSE_WEEKS";
export const GET_COURSE_WEEK = "GET_COURSE_WEEK";
export const UPDATE_COURSE_WEEK = "UPDATE_COURSE_WEEK";

// Days
export const GET_COURSE_DAYS = "GET_COURSE_DAYS";
export const GET_COURSE_DAY = "GET_COURSE_DAY";
export const UPDATE_COURSE_DAY = "UPDATE_COURSE_DAY";

// Reports
export const GET_REPORT_QUESTIONS = "GET_REPORT_QUESTIONS";

// Numbers
export const GET_NUMBERS = "GET_NUMBERS";
