// Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_FAIL = "REGISTER_FAIL";
export const SIGNUP_SUCCESS = "REGISTER_SUCCESS";

// Errors & Messages
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// General info
export const GET_GENERAL_INFO = "GET_GENERAL_INFO";
export const UPDATE_GENERAL_INFO = "UPDATE_GENERAL_INFO";
export const GET_CONTACT_INFO = "GET_CONTACT_INFO";

// Courses
export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const INVERT_COURSE_VISIBILITY = "INVERT_COURSE_VISIBILITY";
export const ADD_COURSE = "ADD_COURSE";
export const UPDATE_COURSE = "ADD_COURSE";

// Weeks
export const GET_COURSE_WEEKS = "GET_COURSE_WEEKS";
export const GET_COURSE_WEEK = "GET_COURSE_WEEK";
export const UPDATE_COURSE_WEEK = "UPDATE_COURSE_WEEK";

// Days
export const GET_COURSE_DAYS = "GET_COURSE_DAYS";
export const GET_COURSE_DAY = "GET_COURSE_DAY";
export const UPDATE_COURSE_DAY = "UPDATE_COURSE_DAY";

// Articles
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLE = "GET_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const INVERT_ARTICLE_VISIBILITY = "INVERT_ARTICLE_VISIBILITY";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";

// Reports
export const GET_REPORT_QUESTIONS = "GET_REPORT_QUESTIONS";
export const CREATE_REPORT = "CREATE_REPORT";
export const GET_REPORTS = "GET_REPORTS";
export const GET_REPORT_BY_DAY_ID = "GET_REPORT_BY_DAY_ID";

// Numbers
export const GET_NUMBERS = "GET_NUMBERS";

// Users
export const GET_USERS = "GET_USERS";
export const INVERT_USER_COURSE_ACCESS = "INVERT_USER_COURSE_ACCESS";

// Screenshots
export const GET_SCREENSHOTS = "GET_SCREENSHOTS";
export const DELETE_SCREENSHOT = "DELETE_SCREENSHOT";
export const ADD_SCREENSHOT = "ADD_SCREENSHOT";
export const UPDATE_SCREENSHOT = "UPDATE_SCREENSHOT";