# Generated by Django 3.2.6 on 2021-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me_list', models.TextField(default='')),
                ('greeting_video', models.FileField(upload_to='general_files')),
                ('psychological_consultation_description', models.TextField(default='')),
                ('whatsapp_number', models.CharField(default='', max_length=32)),
                ('instagram_alias', models.CharField(default='', max_length=32)),
                ('main_page_numbers_form_label', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='general_files')),
            ],
        ),
    ]
