# Generated by Django 3.2.6 on 2021-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='greeting_video',
            field=models.FileField(upload_to='apps\\frontend\\static'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='content',
            field=models.FileField(upload_to='apps\\frontend\\static'),
        ),
    ]
