# Generated by Django 3.2.6 on 2021-08-05 18:03

import apps.courses.helpers.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20210805_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='greeting_video',
            field=models.FileField(upload_to=apps.courses.helpers.functions.UploadToPathAndRename('apps\\frontend\\static')),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='content',
            field=models.ImageField(upload_to=apps.courses.helpers.functions.UploadToPathAndRename('apps\\frontend\\static')),
        ),
    ]
