# Generated by Django 3.2.6 on 2021-08-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20210805_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='main_page_numbers_form_label',
            new_name='main_page_numbers_form_text',
        ),
    ]
