# Generated by Django 3.2.6 on 2021-08-29 22:03

import apps.courses.helpers.functions
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_auto_20210827_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='greeting_video',
            field=models.FileField(null=True, upload_to=apps.courses.helpers.functions.UploadToPathAndRename(pathlib.PureWindowsPath('C:/Users/lllum/Projects/svetlana_website/apps/frontend/src/uploads'))),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='content',
            field=models.ImageField(upload_to=apps.courses.helpers.functions.UploadToPathAndRename(pathlib.PureWindowsPath('C:/Users/lllum/Projects/svetlana_website/apps/frontend/src/uploads'))),
        ),
    ]
