# Generated by Django 3.2.6 on 2021-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_auto_20210830_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='two_course_sale_value',
            field=models.IntegerField(default=100),
        ),
    ]
