# Generated by Django 3.2.6 on 2021-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
