# Generated by Django 3.2.6 on 2021-08-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reportquestion',
            name='text',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
